# ----
# Site

title: Front Girls
description: 
url:
google_analytics_key:
permalink:

collections:
  posts:
    title: Posts
    position: 1

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - event
  - tutorial
  - stuff

categories:
